#!/usr/bin/env python

from __future__ import division,print_function,unicode_literals
from geode.value import parser
from geode import *
import gui
import sys
import re

# Properties
props = PropManager()
mesh = props.add('mesh','').set_required(1)
parser.parse(props,'One-off mesh viewer',positional=[mesh])

# Load
tm = TriMesh()
tm.read(mesh())
mesh = cache(lambda:TriangleSoup(tm.elements()))
X = cache(lambda:tm.X())

# Print information
print('vertices = %d'%tm.n_vertices())
print('edges = %d'%tm.n_edges())
print('faces = %d'%tm.n_faces())

# View
app = gui.QEApp(sys.argv,True)
main = gui.MainWindow(props)
main.view.add_scene('mesh',gui.MeshScene(props,mesh,X,(.2,.2,1),(0,1,0)))
main.init()
app.run()
