#!/usr/bin/env python

from __future__ import division,print_function
from geode import *
import pylab
from matplotlib.patches import Polygon

s = polar(2*pi/6*arange(6))
d = asarray([s[0],s[-1],s[1],s[2],s[2],s[3],s[-1],s[-2]])
p = concatenate([[zeros(2)],cumsum(d,axis=0)])
assert allclose(p[0],p[-1])
p = p[:-1]

if 0:
  ax = pylab.axes()
  for i in arange(-10,10):
    for j in arange(-10,10):
      ax.add_patch(Polygon(p+i*(s[0]+s[1])+j*3*s[2],closed=1,fill='r'))
  ax.set_aspect('equal')
  pylab.xlim(-10,10)
  pylab.ylim(-10,10)
  pylab.show()

if 1:
  z = zeros(2)
  def line(a,b):
    pylab.plot([a[0],b[0]],[a[1],b[1]])
  line(z,2*s[0])
  line(z,2*s[1])
  line(2*s[0],2*s[1])
  line(s[0]+s[-1],s[1]+s[2])
  line(s[0],s[0]+s[1])
  line(s[1],s[0]+s[1])
  line(2*s[0],2*s[0]-s[1])
  line(2*s[1],2*s[1]-s[0])
  pylab.axes().set_aspect('equal')
  pylab.show()
